# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zach Thompson
author:
  name: Zach Thompson
  email: z.douglas.thompson@gmail.com
description: >- 
  Zach's cyber blog.
url: "https://blog.hobo.gg" 
github_username:  zachdthompson

# Build settings
markdown: CommonMarkGhPages
remote_theme: jekyll/minima
plugins:
  - jekyll-feed

google_analytics: G-4M0P86115W
  
minima:
  skin: auto
  social_links:
  - { platform: github,     user_url: "https://github.com/zachdthompson/"}
  - { platform: linkedin,   user_url: "https://www.linkedin.com/in/zachary-d-thompson/"}

header_pages:
  - about.md

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

